name: LeetCode Auto Sync

on:
  schedule:
    - cron: "0 18 * * *"  # Runs daily at 11:30 PM IST
  workflow_dispatch:       # Allows manual run

jobs:
  sync-leetcode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests PyGithub

      - name: Run LeetCode Fetch Script
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          CSRFTOKEN: ${{ secrets.CSRFTOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/leetcode_fetch.py
